//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgenciaAutomotiva
{
    using System;
    using System.Collections.Generic;

    public partial class tb_veiculos
    {
        public int Id { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public short ano { get; set; }
        public short fabricacao { get; set; }
        public string cor { get; set; }
        public byte combustivel { get; set; }
        public bool automatico { get; set; }
        public decimal valor { get; set; }
        public Nullable<bool> situacao { get; set; } // Aceita null
    }

}
